server:
  port: 2000
spring:
  batch:
    job:
      enables: false
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k8a107.p.ssafy.io:3306/moyeo?serverTimezone=UTC
    username: Wujin
    password: wujin1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

notification: http://k8a107.p.ssafy.io:3000/batch/push

flask: http://k8a107.p.ssafy.io:4000
