spring:
  port : 8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k8a107.p.ssafy.io:3306/moyeo?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: tiger
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
