sever:
  port: 443

  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKC12
    key-store-password: moyeo1234

spring:
  port: 8080
  #swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moyeo?serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB
  profiles:
    include: s3, clova

springboot:
  jwt:
    secret: eyJhbGciOiJIUzI1NiIsInR5cCI6ImRhbmltIUAjIn0.eyJzdWIiOiIiLCJuYW1lIjoiIiwiaWF0IjoxNTE2MjM5MDIyfQ.6auDGD6gmIqWWc8jRCy3ZvH4SPElyV4aH0NfIsi11o8
  # 파일 임시 저장 경로
#  servlet:
#    multipart:
#      location: /Users/SSAFY/Desktop/Test
logging:
  level:
    root: info
    com:
      deeping: trace
spring-doc:
  version: v1

