cloud:
  aws:
    credentials:
      access-key: AKIAU3MYXNE4ANS6ZK4Y
      secret-key: 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
    s3:
      bucket: moyeo
    region:
      static: ap-northeast-2
    stack:
      auto: false
